const express = require('express')
const router = express.Router()
const adminController = require(`../controllers/adminController`)
const adminAuth = require(`../Middleware/authMiddleware`)
const upload = require("../Middleware/uploadMiddleware")
router.get(`/login`, adminController.getLogin)
router.post(`/login`, adminController.postLogin)
router.get(`/dashboard`, adminAuth, adminController.getDashboard)
router.get(`/users`, adminAuth, adminController.getUsers)
router.put('/users/:id/block', adminController.blockUser)
router.get("/catagory", adminAuth, adminController.getCategory)
router.post("/catagory", adminAuth, adminController.addCategory)
router.put("/catagory/:id/toggle", adminAuth, adminController.toggleCategory)
router.put("/catagory/:id", adminAuth, adminController.updateCategory)
router.get("/products", adminAuth, adminController.getProducts)
router.post("/products", adminAuth, upload.array("images",5), adminController.addProduct)
router.put("/products/:id/toggle", adminAuth, adminController.toggleProduct)
router.put("/products/:id", adminAuth, upload.array("images",5), adminController.updateProduct)
router.delete("/products/:id/image", adminAuth, adminController.deleteProductImage)
router.put("/products/:id/replaceImage", adminAuth, upload.array("images", 1), adminController.replaceProductImage)
router.get("/coupon", adminAuth, adminController.getCoupon)
router.post("/coupon", adminAuth, adminController.addCoupon)
router.put("/coupon/:id", adminAuth, adminController.updateCoupon)
router.put("/coupon/:id/toggle", adminAuth, adminController.toggleCoupon) 
router.get("/logout", adminController.logout)
router.get('/orders',adminController.getOrders)
router.post('/orders/:id/status', adminController.updateOrderStatus)
router.get('/analytics', adminController.getAnalytics)
module.exports = router

