const express = require("express")
const router = express.Router()
const userController = require("../controllers/userController")
const userAuth = require("../Middleware/userAuthMiddleware")
const noCache = require("../Middleware/cacheMiddleware")
router.get("/register",noCache, userController.getRegister)
router.post("/register", userController.postRegister)
router.get("/login",userController.getLogin)
router.post("/login", userController.postLogin)
router.get("/logout", userController.logout)   
router.get("/shop", userAuth, userController.getShop)
router.get(`/products`,userController.getProducts)
router.get(`/home`,userAuth,userController.getHome)
router.get(`/homeData`,userAuth,userController.getHomeProducts)
router.get(`/product/:id`,userAuth,userController.productDetails)
// router.get(`/profile`,userController.getProfile)
router.get(`/profile`,userAuth,userController.getProfile)
router.patch(`/update-profile`,userController.updateProfile)
router.post(`/add-address`,userController.addAddress)
router.delete("/delete-address/:id", userController.deleteAddress)
router.patch("/edit-address/:id",userController.editAddress)
router.post("/add-cart",userAuth,userController.addToCart)
router.get("/cart",userAuth,userController.getCart)
router.delete("/cart/remove/:productId",userAuth,userController.removeFromCart)
router.patch("/cart/update-cart",userAuth,userController.updateCartQuantity)
router.get("/cart/summary",userAuth,userController.getCartSummary)
router.post("/apply-coupon",userAuth,userController.applyCoupon)
router.patch("/change-password", userController.changePassword)
router.get("/checkout",userAuth,userController.getCheckout)
router.post("/create-order",userController.createRazorPayOrder)
router.post('/verify-payment', userController.verifyPayment)
router.post('/place-order-cod', userController.placeCodOrder)
router.get('/orders',userAuth, userController.getOrders)
router.get("/orders/:id",userAuth, userController.getOrderDetail)
router.post('/orders/:id/cancel', userController.cancelOrder)
router.post('/orders/:id/return', userController.returnOrder)
router.get('/order-success/:orderId',userAuth,userController.getOrderSuccess)
router.get("/",(req,res) =>{
    res.redirect("/login")
})
module.exports = router

