const express = require("express")
const router = express.Router()
const userController = require("../controllers/userController")
const userAuth = require("../Middleware/userAuthMiddleware")
const noCache = require("../Middleware/cacheMiddleware")
const userApiauth = require("../Middleware/userApiMiddleware")
const NoAuth = require("../Middleware/userNoAuthMiddleware")

router.get("/register", NoAuth, noCache, userController.getRegister)
router.post("/register", userController.postRegister)
router.get("/login", NoAuth, userController.getLogin)
router.post("/login", userController.postLogin)
router.get("/logout", userController.logout)
router.get("/shop", userAuth, userController.getShop)
router.get(`/products`, userController.getProducts)
router.get(`/home`, userAuth, userController.getHome)
router.get(`/homeData`, userAuth, userController.getHomeProducts)
router.get(`/product/:id`, userAuth, userController.productDetails)
// router.get(`/profile`,userController.getProfile)
router.get(`/profile`, userAuth, userController.getProfile)
router.patch(`/update-profile`, userController.updateProfile)
router.post(`/add-address`, userApiauth, userController.addAddress)
router.delete("/delete-address/:id", userApiauth, userController.deleteAddress)
router.patch("/edit-address/:id", userApiauth, userController.editAddress)
router.post("/add-cart", userApiauth, userController.addToCart)
router.get("/cart", userAuth, userController.getCart)
router.delete("/cart/remove/:productId", userApiauth, userController.removeFromCart)
router.patch("/cart/update-cart", userApiauth, userController.updateCartQuantity)
router.get("/cart/summary", userAuth, userController.getCartSummary)
router.post("/apply-coupon", userApiauth, userController.applyCoupon)
router.patch("/change-password", userApiauth, userController.changePassword)
router.get("/checkout", userAuth, userController.getCheckout)
router.post("/create-order", userApiauth, userController.createRazorPayOrder)
router.post('/verify-payment', userApiauth, userController.verifyPayment)
router.post('/place-order-cod', userApiauth, userController.placeCodOrder)
router.get('/orders', userAuth, userController.getOrders)
router.get("/orders/:id", userAuth, userController.getOrderDetail)
router.post('/orders/:id/cancel', userApiauth, userController.cancelOrder)
router.post('/orders/:id/return', userApiauth, userController.returnOrder)
router.get('/order-success/:orderId', userAuth, userController.getOrderSuccess)
router.post("/clear-cart", userApiauth, userController.clearCart)
router.get("/", (req, res) => {
    res.redirect("/login")
})
module.exports = router

